#file roles/nginx/tasks/main.yml
---

- name: Include OS-specific variables.
  include_vars: yum_vars.yml
  when: ansible_os_family == "RedHat"

- name: Include OS-specific variables.
  include_vars: apt_vars.yml
  when: ansible_os_family == "Debian"


# - name: get current nginx version
#   shell: nginx -v
#   register: nginx_current_ver
#   ignore_errors: True
#   changed_when: False

- name: delegate to APT system for installation
  include: yum.yml
  # when: nginx_version not in nginx_current_ver.stderr or nginx_first_install and ansible_os_family == "RedHat"
  when: ansible_os_family == "RedHat"

- name: delegate to APT system for installation
  include: apt.yml
  # when: nginx_version not in nginx_current_ver.stderr or nginx_first_install and ansible_os_family == "RedHat"
  when: ansible_os_family == "Debian"


- include: conf.yml

- include: service.yml