#file roles/zabbix_server/handlers/main.yml
---

- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted

- name: restart zabbix-server
  service:
    name: zabbix-server
    state: stop

- name: restart zabbix nginx server
  service:
    name: nginx
    state: restarted
