#file roles/mysql/tasks/yum.yml
---

- name: Add repository
  yum_repository:
    name: mysql
    description: mysql YUM repo
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/6/$basearch/
    gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
    async: yes
    enabled: yes
  tags: packages

- name: Install initializtion require software
  yum:
    name: mysql
    enablerepo: mysql
    state: present

- name: Install initializtion  packages require software
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mysql_packages }}"
