#file roles/zabbix_agent/handlers/main.yml
---

- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted

- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: stop