#file roles/zabbix_server/tasks/configure.yml
---

- name: Place zabbix-server config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    backup: yes
  with_items:
    - { src: zabbix_server.conf.j2, dest: /etc/zabbix/zabbix_server.conf }
  notify:
    - restart zabbix-server

- name: change zabbix web host dir owner
  file:
    path: "{{ zabbix_web_path }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    recurse: yes
    state: directory

- name: change zabbix web configure dir owner
  file:
    path: "{{ zabbix_web_config_path }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0755
    recurse: yes
    state: directory


- name: Place configured file because set up process does not work well.
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix_server.conf.php
    backup: yes

- name: configure zabbix nginx web server
  template:
    src: zabbix_nginx.conf.j2
    dest: "{{ zabbix_web_nginx_conf_path }}"
  notify:
    - restart zabbix nginx server